### ISSUE TITLE
Generator for matchSettings files

### ISSUE THREAD

**Issue by sebasdt** [nils-ost/TMNF-TimeAttackServer#2]
Hi,
The issue I'm experiencing is that the website and the dedicaded server seem to be broken while it doesn't trow any errors.

What I wanted to do is merge all matchSettings into one [file](https://pastebin.com/r4SL7Wiv). 

After restarting the tmnf deamon the website started to trow this error:  "Lost connection to dedicated gameserver! Please contact: Admin". Weirdly enough reverting back to the default playlists its fixed again after a system reboot.
I have to say while this is happening the player can still join and play on the server.

sorry if things arent very clear English isn't my first language.

**Comment by sebasdt** [comment]
Its on me that it wouldn't launch and couldn't get it to work. 
It would be way easier if it would have a option to generate a matchSettings file.

**Comment by nils-ost** [comment]
Hi sebasdt,
I reopend your issue as I like the idea of having a generator for matchSettings files. This might help others to set up their servers as well :)

**Comment by sebasdt** [comment]
Hi,

Yeah its a bit too much manual work if you need to migrate over 100 maps into the file hehe.
In the future It would be handy if the generator has a selection menu of some sort to 
Maybe Its for now a bit advanced, It would be cool if the generator would take i

**Comment by sebasdt** [comment]
Hey!

It has been a while did you have time to take a look or even try things out.

I'm curious on the progress!

**Comment by nils-ost** [comment]
Hi

indeed I came aroud to work on this feature. You are getting an fully interactive MatchSettings editor, where you can just select challenges, add them to the MatchSetting, move them around and so on.

I would say I'm about 50% done with this feature, but currently a bit limited in time...

**Comment by sebasdt** [comment]
Oh that's so cool, I have the time to wait until these awesome features come out.

It's better to take your time to do it right the first time. Also great to hear you are still interested and invested in the project.
I get it, life goes on and thats important too.
Thank you for your time and awesome project!

**Comment by nils-ost** [comment]
Hi @sebasdt,
it's finally done... at least in the current alpha version :)

If you like to try it out, you can find the installer at https://github.com/nils-ost/TMNF-TimeAttackServer/releases/tag/v1.2.0.alpha1
Don't worry to much about the alpha-tag this is because I like to add another feature to the v1.2.0 release than just the Interactive MatchSettings Editor, the alpha version shouldn't break anything existing. But I wanted you to be able to test out the MatchSettings Editor.

BTW: I also wrote a small README on the usage, you can find it here: https://github.com/nils-ost/TMNF-TimeAttackServer/blob/dev-v1.2.0/docs/matchsettingseditor.md

Have fun :)

**Comment by sebasdt** [comment]
Hi,

WOW! Thank you so so much! 
I see it has been a lot of work to make the editor possible!
I'll check it out whenever I got the time.
The setup I had changed a bit since the last time and am in the middle of reworking my lab.

Again, thank you for your work!

**Comment by nils-ost** [comment]
Now released with version 1.2.0
