### ISSUE TITLE
Handover to Fabric failing due to having non standard ssh config

### ISSUE THREAD

**Issue by sebasdt** [nils-ost/TMNF-TimeAttackServer#4]
Hi,

After a long time, I tried to install the time attack server but the install script failed.
This is due to me have "hardened" my ssh config. this means my SSH port is on a custom port.

Here below Is the fault I'm getting, this isn't the only one as there are multiple that look the same.
![image](https://github.com/nils-ost/TMNF-TimeAttackServer/assets/67417070/d3ce0037-7f3c-411b-8688-dbe91d753acd)

My operating system is Ubuntu 22.04, Is there a way to specify a custom SSH port?
Thank you!

edit:
My setup also uses a ssh passkey but that didnt affect installation for me.

**Comment by nils-ost** [comment]
Hi @sebasdt 
yes the installer is meant to be used on a fresh install, not on an already hardened one. But you can try the following:

Instead of just running the installer, you can extract it. Modify the initial exec script, and run that one manually. So for example for the latest release this would look like the following (if your SSH listening port is 2222)

```
wget https://github.com/nils-ost/TMNF-TimeAttackServer/releases/download/v1.2.1/tmnf-tas-installer_v1.2.1.run
chmod +x tmnf-tas-installer_v1.2.1.run
./tmnf-tas-installer_v1.2.1.run --keep --noexec
cd tmnf-tas
sed -i 's/root@localhost/root@localhost:2222/g' installer.sh
./installer.sh
```

The sed command is just searching for all appearances of root@localhost and is replacing it by root@localhost:2222
Those are the connection strings, that are handed over to fabric. Hope that helps and works.

By the way: The passkey shouldn't affect the installer, as it is generating a new ssh-key for each run, saving you existing ones, placing the generated one instead your usual ones, using that for the installation, and than rolling back to your personal keys ;)

Hope that works, let me know :)

**Comment by sebasdt** [comment]
That did the trick!
thank you!
